### PR TITLE
Feature/services and code improvements

### PR DESCRIPTION
**Pull request by Sparky-Kitty**
* Small progress on error handling for service bump/create.
* Started work on API call for ServiceSlotSearch, mostly for the My Listings>Notification section of purchases service notifications.

### CODE REVIEW

**Comment by Sparky-Kitty** [comment]
Anonymous on My Services will prompt to Login, else shows content based on logged in user. Since the listings page has started relying on the AuthState, the page would throw an error about userId being null.
- Anonymous
image
- Logged in
image

The usage of API in service-notification.component (while logged in) requires the changes in [shared PR 2](https://github.com/SanctuaryTeam/shared/pull/2/files)

**Comment by d4search** [comment]
PR Fails to build.

**Comment by Sparky-Kitty** [comment]
> PR Fails to build.

What does it check? How can I ensure my checks don't fail?

**Comment by d4search** [comment]
`docker run web-api yarn build`

**Comment by Sparky-Kitty** [comment]
> `docker run web-api yarn build`

image
 
Is it not finding the matching package from shared?

**Comment by d4search** [comment]
This error has to do with the yarn link, try running `docker compose run web-app yarn unlink @sanctuaryteam/shared` and if need be remove ```ts
      "@sanctuaryteam/shared": [
        "../shared/src"
      ]
      ``` from the merged json file, then run the build command again. I will look into how to make this more seamless.

**Comment by d4search** [comment]
Can you see if changing it to

```ts
,
      "@sanctuaryteam/shared": [
        "../shared/src",
        "./shared/src"
      ]
```

works?

**Comment by Sparky-Kitty** [comment]
I'll check!

**Comment by d4search** [comment]
Tsconfig should use the first path that resolves, locally it will use the relative directory above the app, but in docker it will resolve the symlink mount correctly.

**Pull request closed without merging**
