### PR TITLE
Made some progress on the My Services page:

### PR DESCRIPTION
**Pull request by Sparky-Kitty**
* Basic layout
  * Create New Service has fields for Realm, Tags, Title, Content, and MaxSlots.
  * Notifications has fields for showing the rating score and service title, and has room to store the name to show after accepted.
    * Found in service-notification.component (ServiceOffer)
  * Copied basic layout of search-result.component (SearchResult) into service-listing.component (ServiceListing) * Replaced buttons with Bump and Delete Listing

image

### CODE REVIEW

**Comment by d4search** [comment]
Just a few things not related to the page:

- Remove yarn.lock from gitignore we do want this file in our repository
- Not sure why your typescript package was updated, but also please unstage or revert the yarn.lock file.

**Comment by d4search** [comment]
- Investigate using `ServerTypeInput` server-type-input.component.tsx for the realm selector
- Put the realm selector on the same line as the tag selector
- Move the Slot selection, Create, and Clear buttons down under content

**Comment by Sparky-Kitty** [comment]
I am ready for some code review.

**Comment by d4search** [comment]
Let's get this merged into develop, so these must be changed:

- Create a PR for the API changes, remove the abcd folder
- Move the SERVICE_TAGS structure to the shared folder in the services.ts. If it needs to be renamed to fit in, please follow convention.
- Remove yarn.lock changes

More to come...

**Pull request merged**
